### ISSUE TITLE
Contributions Feature

### ISSUE THREAD

**Issue by fwoelm** [OpenlyOne/openly#269]
Implement basic version of pull requests.

- [x] User can create a contribution (pull request)
- [x] Files are copied from last commit
- [x] User can browse files in contribution
- [x] User can view file infos for files in contribution: ~~Sun, Jan 27~~ Mon, Jan 28
- [x] User can force sync files in contribution: Mon, Jan 28
- [ ] User can restore past versions of files in contribution: ~~Mon, Jan 28~~ postponed: see #276 
- [x] User can view side-by-side diffs in contribution (#275): Mon, Jan 28
- [x] User can review changes made in pull request: Wed, Jan 30
- [x] User can merge pull request (overwriting any uncaptured changes) — there is no 3-way merge support in this first implementation: ~~Thu, Jan 31~~ Fri, Feb 1
- [x] Contribution indicates status: open vs accepted: Thu, Jan 31
- [ ] User can reply to contribution: ~~Fri, Feb 1~~ postponed: see #280 

And:
- [ ] Email is sent to project team when contribution is created: postponed
- [ ] Email is sent to contribution creator & project team when contribution is accepted: postponed

**Comment by fwoelm** [comment]
Resolved by #289
